// Last updated: 8/3/2025, 9:52:38 AM
/*Generated By Rishabh*/
class Solution {
    public int minElement(int[] nums) {
        int ans = Integer.MAX_VALUE;

        for (int i = 0; i < nums.length; i++) {
            int num = nums[i];
            int digitSum = 0;

            while (num > 0) {
                digitSum += num % 10;
                num /= 10;
            }

            ans = Math.min(ans, digitSum);
        }

        return ans;
    }
}
