// Last updated: 8/3/2025, 9:52:40 AM
/*Generated by Rishabh And GPT */



class Solution {

    /**
     * Finds which number (x or y) is closer to the target z.
     * 
     * @param x First number
     * @param y Second number
     * @param z Target number
     * @return 1 if x is closer, 2 if y is closer, 0 if both are equally close
     */
    public int findClosest(int x, int y, int z) {
        int distanceX = Math.abs(x - z);
        int distanceY = Math.abs(y - z);

        if (distanceX < distanceY) {
            return 1; // x is closer
        } else if (distanceY < distanceX) {
            return 2; // y is closer
        } else {
            return 0; // both are equally close
        }
    }
}
